services:

  next-app:
    container_name: F1-Dashboard-Client
    depends_on:
      - server
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    restart: always
    ports:
      - 3000:3000

  mongodb:
    container_name: F1-Dashboard-MongoDB
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./db:/data/db

  server:
    container_name: F1-Dashboard-Server
    depends_on:
      - mongodb
    image: bun
    build:
      context: ./server
    volumes:
      - ./server/:/app/server/
      - /app/server/node_modules
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 4000:4000
    expose:
      - 4000
    environment:
      - BUN_PORT=4000
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT


