FROM oven/bun:1-alpine

# Copy the lock and package file
COPY bun.lockb . 
COPY package.json . 

# Install dependencies
RUN bun install --frozen-lockfile

# Copy your source code
# If only files in the src folder changed, this is the only step that gets executed!
COPY src ./src 

# Build your application
RUN bun build --entrypoints ./src/index.ts --outdir ./dist --target bun


CMD ["bun", "dist/index.js"]